version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/var/www
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
#    ports:
#      - "9999:80"
    expose:
      - "9000"
    links:
      - "db:mysql-server"
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    restart: always
    networks:
      - backend

  db:
    image: yobasystems/alpine-mariadb:latest
    restart: always
    ports:
      - "${FORWARD_DB_PORT:-3386}:3306"
#    command: mysqld --max_allowed_packet=32505856 --default-authentication-plugin=mysql_native_password
    #    command: --max_allowed_packet=32505856 --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:
networks:
  backend:
    driver: bridge
