name: Deploy manual
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Entorno a desplegar'
        required: true
        default: 'development'
      tag:
        description: 'Tag de la aplicación'
        required: true
        default: 'v'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: deploy to develop
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    env:
      DEPLOY_URL: ${{ github.event.inputs.environment }}
    permissions:
      contents: read
      packages: read

    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        env:
          USER_MACHINE: ${{ secrets.USERNAME }}
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.event.inputs.tag }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: USER_MACHINE,REGISTRY,IMAGE_NAME,IMAGE_TAG
          script: |
            cd /home/$USER_MACHINE/drupal
            export REGISTRY=${REGISTRY}
            export IMAGE_NAME=${IMAGE_NAME}
            export IMAGE_TAG=${IMAGE_TAG:1}
            docker pull $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
            docker-compose up -d
            docker-compose exec app drush config:import --yes
            docker-compose exec app drush cr
            echo $IMAGE_TAG > .deployed
